# Generated by Django 4.1.6 on 2024-12-23 08:35

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dam', models.CharField(max_length=64, null=True, unique=True, verbose_name='种质编号')),
            ],
        ),
        migrations.CreateModel(
            name='ExcelNet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='file')),
            ],
        ),
        migrations.CreateModel(
            name='GermImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=64, verbose_name='序号')),
                ('germ_id', models.CharField(max_length=64, verbose_name='种质编号')),
                ('germ_image', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='种质图像')),
            ],
        ),
        migrations.CreateModel(
            name='germplasm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('germ_id', models.CharField(max_length=10, null=True, verbose_name='编号')),
                ('time', models.DateField(max_length=64, null=True, verbose_name='保存时间')),
                ('provenance', models.CharField(max_length=4, null=True, verbose_name='种源')),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='纬度')),
                ('average_altitude', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='平均海拔')),
                ('annual_average_temperature', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='年平均气温')),
                ('annual_precipitation', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='年降水量')),
                ('average_annual_sunshine_duration', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='年均日照时数')),
                ('frost_free_period', models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='无霜期')),
                ('relative_humidity', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='相对湿度')),
                ('total_height', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='树高')),
                ('diameter_at_breast_height', models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='胸径')),
                ('cone_type', models.CharField(max_length=4, null=True, verbose_name='球果类型')),
                ('cone_bract_scale_shape', models.CharField(max_length=2, null=True, verbose_name='苞鳞形状')),
                ('the_split_of_bracts_and_scales_in_immature_cones', models.CharField(max_length=2, null=True, verbose_name='张裂程度')),
                ('cone_length', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='球果长度')),
                ('cone_width', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='球果宽度')),
                ('cone_volume', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='球果体积')),
                ('cone_shape_coefficient', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='果形系数')),
                ('bract_scale_length', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='苞鳞长度')),
                ('bract_scale_width', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='苞鳞宽度')),
                ('bract_scale_length_width_ratio', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='苞鳞长宽比')),
                ('new_leaf_white_powder', models.CharField(max_length=3, null=True, verbose_name='新叶白粉')),
                ('old_leaf_white_powder', models.CharField(max_length=3, null=True, verbose_name='老叶白粉')),
                ('leaf_color', models.CharField(max_length=4, null=True, verbose_name='颜色')),
                ('serration_density', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='锯齿密度')),
                ('needle_hardness', models.CharField(max_length=1, null=True, verbose_name='针叶硬度')),
                ('leaf_length', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='针叶长度')),
                ('leaf_width', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='针叶宽度')),
                ('leaf_index', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='叶形指数')),
                ('volume_of_wood', models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='材积')),
                ('wet_weight_of_wood', models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='木材湿重')),
                ('dry_weight_of_wood', models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='木材干重')),
                ('water_absorption_of_wood', models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='木材吸水率')),
                ('wood_density', models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='木材密度')),
                ('thousand_seed_weight', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='千粒重')),
                ('rate_of_emergence', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='出苗率')),
            ],
        ),
        migrations.CreateModel(
            name='LmsUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.CharField(max_length=254, verbose_name='邮箱')),
                ('mobile', models.BigIntegerField(blank='True', verbose_name='手机')),
            ],
        ),
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=64, unique=True, verbose_name='试验林编号')),
                ('Fam_num', models.CharField(max_length=64, null=True, verbose_name='家系号')),
                ('Rep', models.CharField(max_length=64, verbose_name='重复')),
                ('Site', models.CharField(max_length=64, verbose_name='场地')),
                ('Block', models.CharField(max_length=64, verbose_name='区组号')),
                ('Plot', models.CharField(max_length=64, verbose_name='地点')),
                ('blk_num', models.CharField(max_length=64, verbose_name='区组编号')),
            ],
        ),
        migrations.CreateModel(
            name='Sire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sire', models.CharField(max_length=64, null=True, unique=True, verbose_name='种质编号')),
            ],
        ),
        migrations.CreateModel(
            name='PedigreeTree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('pedigree_name', models.CharField(max_length=64, null=True, verbose_name='家系名称')),
                ('germ_id', models.CharField(max_length=64, unique=True, verbose_name='种质编号')),
                ('Dam', models.ForeignKey(blank=True, db_column='Dam', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damAll', to='app01.dam', to_field='Dam', verbose_name='母本')),
                ('Sire', models.ForeignKey(blank=True, db_column='Sire', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sireAll', to='app01.sire', to_field='Sire', verbose_name='父本')),
            ],
        ),
        migrations.CreateModel(
            name='PedigreeMPTT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('germ_id', models.CharField(max_length=64, unique=True, verbose_name='种质编号')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('Dam', mptt.fields.TreeForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_dam', to='app01.dam', verbose_name='母本')),
                ('Sire', mptt.fields.TreeForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_sire', to='app01.sire', verbose_name='父本')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='pedigree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('germ_id', models.CharField(max_length=64, null=True, verbose_name='种质编号')),
                ('pedigree_name', models.CharField(max_length=64, null=True, verbose_name='家系名称')),
                ('parent_f', models.CharField(max_length=64, null=True, verbose_name='父本')),
                ('parent_m', models.CharField(max_length=64, null=True, verbose_name='母本')),
                ('pedigree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.germplasm')),
            ],
        ),
        migrations.CreateModel(
            name='half_sib',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('germ_id', models.CharField(max_length=64, verbose_name='种质编号')),
                ('pedigree_name', models.CharField(max_length=64, verbose_name='家系名称')),
                ('parent_m', models.CharField(max_length=64, verbose_name='母本')),
                ('pedigree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.germplasm')),
            ],
        ),
        migrations.CreateModel(
            name='PlantTree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('year', models.IntegerField(verbose_name='保存年份')),
                ('Height', models.CharField(max_length=64, null=True, verbose_name='年份树高')),
                ('dbh', models.CharField(max_length=64, null=True, verbose_name='年份胸径')),
                ('volume_of_wood', models.DecimalField(decimal_places=5, max_digits=6, null=True, verbose_name='材积')),
                ('p_id', models.ForeignKey(db_column='p_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app01.plantation', to_field='p_id', verbose_name='试验林编号')),
            ],
            options={
                'unique_together': {('p_id', 'year')},
            },
        ),
    ]
